name: Main Workflow
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.7.0]

    steps:
      
      - uses: actions/checkout@v2
      
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: 'Step #1 - Minify Action'
        uses: jossydevers/minify-action@v1.0.1
        with:
          directory: 'dist/cron-expression-input.js'
          output: 'release/src/'
        
      - name: 'Step #2 - Commit Action'
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Github Action: Pipeline"
          branch: ${{ github.ref }}
          
